### ISSUE TITLE
"on leave"

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmhc-homebase#10]
If a volunteer's status is changed from "active" to "on leave," they are still on the Master schedule and are continuing to be added to each new published week.

**Comment by oradwan** [comment]
Poking through this, the code looks somewhat poorly factored to fix this easily - are any of the other devs active on this tracker? I'm not sure of the exact vision y'all have for the model here - could fix this issue in the dbMasterSchedule persistence layer (basically filter the get_master_shifts call) or higher up in when we choose to display that. My picture is that for any activity, you'd want to drop people who are on leave...

**Comment by oradwan** [comment]
I was going to fix this - but I'm pretty lost. 

I see a contract in dbPersons which is using 'Person' objects - but then someone has changed it to also sometimes be associative arrays keyed on the fields (see get_persons() in dbMasterSchedule). 

This is less than ideal - I'm worried that any way of doing this is just going to end up fixing this in a somewhat hacky way that people using the thing down the line are going to mess up... And my PHP is a little rusty to refactor the whole thing tonight... I'll aim for a pull request tonight if I get anywhere.

**Comment by megandalster** [comment]
As of right now, when you remove a person from the master schedule, they will be automatically removed from future calendar weeks.  But it doesn't also remove a newly-inactive person from the master schedule itself.  I will change the software to remove a person from the master schedule and all future calendar weeks whenever you change their status from "active".  

But at the same time, I suggest we consider the reverse situation -- that is, changing the software so that it adds a person to all future calendar weeks whenever you add a newly-active person to the master schedule.  (But it still won't do any master-scheduling of that person.)

What do you think?

**Comment by gnoonan** [comment]
I really like that idea. Thank you.

Raymond Ruby
House Manager

Ronald McDonald House Charities of Maine
250 Brackett Street, Portland, ME 04102
Phone 207-780-6282  ext. 316
Fax  207-780-0198
www.rmhcmaine.orghttp://www.rmhcmaine.org/

Don't miss the purses, accessories, gift certificates, and much more  at our 11th Annual Purses with Purpose, etc. luncheonon Thursday, June 2 in Falmouth!http://rmhcmaine.org/10th-annual-purses-with-purpose-etc-funraiser/
